name: Build Python Wheel

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install build

    - name: Setup
      run: pip install -r dynamodbEntities/requirements.txt
    - name: Build
      run: pip install build; cd dynamodbEntities; python -m build; cd ..
    

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-wheel
        path: dynamodbEntities/dist/*.whl
